import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter,useNavigate,useParams,useLocation,Link,Routes,Route} from "react-router-dom";
import "./index.css";

const API="https://fakestoreapi.com/products";
const Ctx=React.createContext();
function ShopProvider({children}){
 const [products,setProducts]=useState([]),[cart,setCart]=useState(()=>JSON.parse(localStorage.getItem("cart")||"[]")),[wish,setWish]=useState(()=>JSON.parse(localStorage.getItem("wish")||"[]"));
 useEffect(()=>{fetch(API).then(r=>r.json()).then(setProducts).catch(()=>setProducts([]))},[]);
 useEffect(()=>localStorage.setItem("cart",JSON.stringify(cart)),[cart]); useEffect(()=>localStorage.setItem("wish",JSON.stringify(wish)),[wish]);
 const add=(p)=>setCart(c=>{let x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});
 const inc=id=>setCart(c=>c.map(i=>i.id===id?{...i,qty:i.qty+1}:i)), dec=id=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.max(1,i.qty-1)}:i)), remove=id=>setCart(c=>c.filter(i=>i.id!==id));
 const toggle=p=>setWish(w=>w.some(i=>i.id===p.id)?w.filter(i=>i.id!==p.id):[...w,p]);
 return <Ctx.Provider value={{products,cart,wish,add,inc,dec,remove,toggle}}>{children}</Ctx.Provider>
}
const money=n=>`$${n.toFixed(2)}`;
function Nav(){const {cart,wish}=React.useContext(Ctx);return <nav><Link className="brand" to="/">ETHIO<span>SHOP</span></Link><div className="links"><Link to="/">Home</Link><Link to="/shop">Shop</Link><Link to="/wishlist">♡ Wishlist ({wish.length})</Link><Link to="/cart">🛒 Cart ({cart.reduce((a,i)=>a+i.qty,0)})</Link></div></nav>}
function ProductCard({p}){const {wish,add,toggle}=React.useContext(Ctx),fav=wish.some(x=>x.id===p.id);return <article className="card"><button className="heart" onClick={()=>toggle(p)}>{fav?"♥":"♡"}</button><Link to={`/product/${p.id}`}><div className="pic"><img src={p.image}/></div><div className="info"><small>{p.category}</small><h3>{p.title}</h3><div className="rating">★ {p.rating?.rate||0} <span>({p.rating?.count||0})</span></div><strong>{money(p.price)}</strong></div></Link><button className="add" onClick={()=>add(p)}>Add to cart</button></article>}
function Home(){const {products}=React.useContext(Ctx);return <><section className="hero"><div><p className="eyebrow">WELCOME TO ETHIOSHOP</p><h1>Shop smart.<br/><em>Live better.</em></h1><p>Discover quality products at simple prices. Browse, save your favorites and checkout in a few clicks.</p><Link className="primary" to="/shop">Shop now →</Link></div><div className="hero-art">🛍️</div></section><section className="section"><div className="section-head"><div><p className="eyebrow">CURATED FOR YOU</p><h2>Featured products</h2></div><Link to="/shop">View all →</Link></div><div className="grid">{products.slice(0,8).map(p=><ProductCard key={p.id} p={p}/>)}</div></section></>}
function Shop(){const {products}=React.useContext(Ctx);const [q,setQ]=useState(""),[cat,setCat]=useState("all"),[sort,setSort]=useState("default");let cats=[...new Set(products.map(p=>p.category))];let list=products.filter(p=>p.title.toLowerCase().includes(q.toLowerCase())&&(cat==="all"||p.category===cat));if(sort==="low")list.sort((a,b)=>a.price-b.price);if(sort==="high")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating.rate-a.rating.rate);return <section className="section shop"><div className="section-head"><div><p className="eyebrow">OUR COLLECTION</p><h2>All products</h2></div></div><div className="filters"><input placeholder="Search products..." value={q} onChange={e=>setQ(e.target.value)}/><select value={cat} onChange={e=>setCat(e.target.value)}><option value="all">All categories</option>{cats.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="default">Sort by</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="rating">Top rated</option></select></div>{list.length?<div className="grid">{list.map(p=><ProductCard key={p.id} p={p}/>)}</div>:<div className="empty">No products found.</div>}</section>}
function Product(){const {id}=useParams(),{products,add,toggle,wish}=React.useContext(Ctx),p=products.find(x=>x.id===Number(id));if(!p)return <div className="loading">Loading product...</div>;return <section className="detail"><div className="detail-img"><img src={p.image}/></div><div className="detail-copy"><small>{p.category}</small><h1>{p.title}</h1><div className="rating big">★ {p.rating.rate} <span>{p.rating.count} ratings</span></div><h2>{money(p.price)}</h2><p>{p.description}</p><div className="actions"><button className="primary" onClick={()=>add(p)}>Add to cart</button><button className="secondary" onClick={()=>toggle(p)}>{wish.some(x=>x.id===p.id)?"♥ Saved":"♡ Add to wishlist"}</button></div></div></section>}
function Wishlist(){const {wish}=React.useContext(Ctx);return <section className="section"><div className="section-head"><div><p className="eyebrow">YOUR SAVED ITEMS</p><h2>Wishlist</h2></div></div>{wish.length?<div className="grid">{wish.map(p=><ProductCard key={p.id} p={p}/>)}</div>:<div className="empty">Your wishlist is empty.<br/><Link to="/shop">Explore products →</Link></div>}</section>}
function Cart(){const {cart,inc,dec,remove}=React.useContext(Ctx),sub=cart.reduce((a,i)=>a+i.price*i.qty,0),delivery=cart.length?5:0;return <section className="section"><div className="section-head"><div><p className="eyebrow">YOUR BAG</p><h2>Shopping cart</h2></div></div>{!cart.length?<div className="empty">Your cart is empty.<br/><Link to="/shop">Start shopping →</Link></div>:<div className="cart-layout"><div>{cart.map(i=><div className="cart-item" key={i.id}><img src={i.image}/><div><Link to={`/product/${i.id}`}><h3>{i.title}</h3></Link><p>{money(i.price)}</p><div className="qty"><button onClick={()=>dec(i.id)}>−</button><b>{i.qty}</b><button onClick={()=>inc(i.id)}>+</button></div></div><button className="remove" onClick={()=>remove(i.id)}>Remove</button></div>)}</div><aside className="summary"><h3>Order summary</h3><p><span>Subtotal</span><b>{money(sub)}</b></p><p><span>Delivery</span><b>{money(delivery)}</b></p><hr/><p className="total"><span>Total</span><b>{money(sub+delivery)}</b></p><Link className="primary full" to="/checkout">Proceed to checkout</Link></aside></div>}</section>}
function Checkout(){const {cart}=React.useContext(Ctx),nav=useNavigate(),sub=cart.reduce((a,i)=>a+i.price*i.qty,0),[done,setDone]=useState(false);if(done)return <div className="success"><div>✓</div><h1>Order placed!</h1><p>Thank you for shopping with EthioShop.</p><Link className="primary" to="/">Continue shopping</Link></div>;if(!cart.length)return <div className="empty">Your cart is empty. <Link to="/shop">Shop now →</Link></div>;return <section className="checkout"><div><p className="eyebrow">FINAL STEP</p><h1>Checkout</h1><form onSubmit={e=>{e.preventDefault();setDone(true);localStorage.removeItem("cart")}}><label>Full name<input required placeholder="Your name"/></label><label>Email<input type="email" required placeholder="you@example.com"/></label><label>Phone<input required placeholder="+251 9..."/></label><label>Delivery address<textarea required placeholder="Addis Ababa, Ethiopia"/></label><label>Payment method<select><option>Cash on delivery</option><option>Card (demo)</option></select></label><button className="primary full">Place order</button></form></div><aside className="summary"><h3>Your order</h3>{cart.map(i=><p key={i.id}><span>{i.title.slice(0,24)} × {i.qty}</span><b>{money(i.price*i.qty)}</b></p>)}<hr/><p className="total"><span>Total</span><b>{money(sub+5)}</b></p></aside></section>}
function App(){return <><Nav/><main><Routes><Route path="/" element={<Home/>}/><Route path="/shop" element={<Shop/>}/><Route path="/product/:id" element={<Product/>}/><Route path="/wishlist" element={<Wishlist/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<Checkout/>}/></Routes></main><footer>© 2026 EthioShop · React Data-Driven Store</footer></>}
createRoot(document.getElementById("root")).render(<BrowserRouter><ShopProvider><App/></ShopProvider></BrowserRouter>);
